import "./globals.css";
import { Montserrat } from "next/font/google";
import Navigation from "./Components/Navigation";
import Footer from "./Components/Footer";

const monserrat = Montserrat({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Lubricantes Especiales Del Perú",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
        <link
          rel="apple-touch-icon"
          href="/apple-icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
      </head>
      <body className={monserrat.className}>
        <Navigation />
        <main className="min-h-screen">{children}</main>
        <Footer></Footer>
      </body>
    </html>
  );
}
