import "./globals.css";
import { Montserrat } from "next/font/google";
import Navigation from "./Components/Navigation";
import Footer from "./Components/Footer";

const monserrat = Montserrat({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Lubricantes Especiales Del Perú",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={monserrat.className}>
        <Navigation />
        <div className="flex flex-col min-h-screen">{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
