import './globals.css'
import { Inter } from 'next/font/google'
import Navigation from './Components/Navigation'
import Footer from './Components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Lubricantes Especiales Del Perú',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation/>
        <div className='flex flex-col min-h-screen'>
          {children}
        </div>        
        <Footer></Footer>
        </body> 
    </html>
  )
}
